# Generated by Django 6.0.4 on 2026-05-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('not done', 'Not Done'), ('in process', 'In Process'), ('done', 'Done')], default='not_done', max_length=20),
        ),
    ]
