# Generated by Django 6.0.4 on 2026-05-05 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_assignment_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='student',
        ),
    ]
