# Generated by Django 6.0.4 on 2026-05-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_assignment_status_remove_assignment_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='programme',
        ),
        migrations.AddField(
            model_name='student',
            name='programmes',
            field=models.ManyToManyField(related_name='students', to='api.programme'),
        ),
    ]
