# Generated by Django 6.0.4 on 2026-05-11 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_student_programme_student_programmes'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
