# Generated by Django 6.0.4 on 2026-05-24 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='has_changed_password',
            field=models.BooleanField(default=False),
        ),
    ]
