# Generated by Django 6.0.4 on 2026-05-31 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_student_has_changed_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Programme',
            new_name='Subject',
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='programme',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='programme',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='programmes',
            new_name='subjects',
        ),
    ]
