# Generated by Django 6.0.4 on 2026-06-01 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_programme_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='enrollment_key',
            field=models.CharField(default='samspass123', max_length=50),
            preserve_default=False,
        ),
    ]
