# Generated by Django 6.0.4 on 2026-06-02 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_subject_enrollment_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_head_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
