# Generated by Django 6.0.4 on 2026-06-07 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_passwordresetotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(max_length=20)),
                ('item_id', models.IntegerField()),
                ('milestone', models.IntegerField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='api.student')),
            ],
            options={
                'unique_together': {('student', 'item_type', 'item_id', 'milestone')},
            },
        ),
    ]
